dataprep:
	python process_alcohol_drug.py
	python process_demographics.py
	python process_health.py
	python process_itemlevel.py
	python cleanup_items_for_mirt_cv.py
	python mk_surveydata_file.py
cleanup:
	python cleanup_items_for_mirt_cv.py Discovery_12-15-2016 40 1
